/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.Date;
import javax.swing.JOptionPane;
import metier.Pays;
import metier.VIP;
import modele.ModeleJComboBox;

/**
 *
 * @author cyrille
 */
public class FenetreSaisie extends javax.swing.JDialog {

    private VIP vip;
    private boolean etatSortie;
    private ModeleJComboBox leModelCombo;
    
    public FenetreSaisie(java.awt.Frame parent, VIP vip,ModeleJComboBox leModelCombo) {
        super(parent, true);  // mode modal       
        this.vip = vip;
        this.leModelCombo = leModelCombo;
        etatSortie = false;
        initComponents();
    }
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCodeStatut = new javax.swing.ButtonGroup();
        buttonGroupCivilite = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lbNomVip = new javax.swing.JLabel();
        lbPrenomVip = new javax.swing.JLabel();
        lbCiviliteVip = new javax.swing.JLabel();
        lbDateNaissanceVip = new javax.swing.JLabel();
        lbLieuNaissanceVip = new javax.swing.JLabel();
        lbCodeRoleVip = new javax.swing.JLabel();
        lbNomPaysVip = new javax.swing.JLabel();
        lbCodeStatutVip = new javax.swing.JLabel();
        jTFNomVip = new javax.swing.JTextField();
        jTFPrenomVip = new javax.swing.JTextField();
        jComboBoxNomPays = new javax.swing.JComboBox<>();
        jRbMarie = new javax.swing.JRadioButton();
        jRbCelibataire = new javax.swing.JRadioButton();
        jRbFemme = new javax.swing.JRadioButton();
        jRbHomme = new javax.swing.JRadioButton();
        jTFLieuNaissanceVip = new javax.swing.JTextField();
        jRbActeur = new javax.swing.JRadioButton();
        jRbRealisateur = new javax.swing.JRadioButton();
        btValid = new javax.swing.JButton();
        jDCDateNaissance = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNomVip.setText("Nom");

        lbPrenomVip.setText("Prenom");

        lbCiviliteVip.setText("Civilité");

        lbDateNaissanceVip.setText("Date de naissance");

        lbLieuNaissanceVip.setText("Lieu de naissance");

        lbCodeRoleVip.setText("Code role");

        lbNomPaysVip.setText("Nom pays");

        lbCodeStatutVip.setText("Code statut");

        jTFNomVip.setMinimumSize(new java.awt.Dimension(80, 20));
        jTFNomVip.setPreferredSize(new java.awt.Dimension(80, 20));
        jTFNomVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomVipActionPerformed(evt);
            }
        });

        jComboBoxNomPays.setModel(leModelCombo);
        jComboBoxNomPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomPaysActionPerformed(evt);
            }
        });

        buttonGroupCodeStatut.add(jRbMarie);
        jRbMarie.setText("Marié(e)");

        buttonGroupCodeStatut.add(jRbCelibataire);
        jRbCelibataire.setText("Célibataire");

        buttonGroupCivilite.add(jRbFemme);
        jRbFemme.setText("Femme");

        buttonGroupCivilite.add(jRbHomme);
        jRbHomme.setText("Homme");

        jTFLieuNaissanceVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFLieuNaissanceVipActionPerformed(evt);
            }
        });

        jRbActeur.setText("Acteur");

        jRbRealisateur.setText("Réalisateur");

        btValid.setText("Valider");
        btValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidActionPerformed(evt);
            }
        });

        jDCDateNaissance.setDateFormatString("yyyy MM dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDateNaissanceVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCodeStatutVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCiviliteVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbLieuNaissanceVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCodeRoleVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNomPaysVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPrenomVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNomVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbActeur)
                            .addComponent(jRbMarie)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFNomVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFPrenomVip))
                            .addComponent(jDCDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxNomPays, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFLieuNaissanceVip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jRbFemme, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRbHomme)
                                    .addComponent(jRbRealisateur)
                                    .addComponent(jRbCelibataire)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btValid)))
                .addGap(10, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomVip)
                    .addComponent(jTFNomVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrenomVip)
                    .addComponent(jTFPrenomVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCiviliteVip)
                    .addComponent(jRbFemme)
                    .addComponent(jRbHomme))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDateNaissanceVip)
                    .addComponent(jDCDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLieuNaissanceVip)
                    .addComponent(jTFLieuNaissanceVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodeRoleVip)
                    .addComponent(jRbActeur)
                    .addComponent(jRbRealisateur))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomPaysVip)
                    .addComponent(jComboBoxNomPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodeStatutVip)
                    .addComponent(jRbMarie)
                    .addComponent(jRbCelibataire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btValid)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNomPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomPaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNomPaysActionPerformed

    private void jTFNomVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomVipActionPerformed

    private void btValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidActionPerformed
        // TODO add your handling code here:
        try {
            if (jTFNomVip.getText().isEmpty()) {
                throw new Exception("champ Nom Vip vide");
            }
            vip.setNomVip(jTFNomVip.getText());
            
            if (jTFPrenomVip.getText().isEmpty()) {
                throw new Exception("champ Prenom Vip vide");
            }
            vip.setPrenomVip(jTFPrenomVip.getText());
            
             if (!jRbFemme.isSelected() && !jRbHomme.isSelected() ) {
                throw new Exception("champ Civilité vide");
            }
             else{
                 if(!jRbFemme.isSelected()){
                     vip.setCivilite("Homme");
                 }
                 else{
                     vip.setCivilite("Femme");
                 }
            }
            if(jDCDateNaissance.getCalendar()==null){
                 throw new Exception("champ Date de naissance mal rempli");
            }
            java.sql.Date temp = new java.sql.Date(jDCDateNaissance.getDate().getTime());
            vip.setDateNaissance(temp);
            
             if(jTFLieuNaissanceVip.getText().isEmpty())
             {
                 throw new Exception("champ Ville de naissance vide");
             }
             vip.setLieuNaissance(jTFLieuNaissanceVip.getText());
            
            if(!jRbActeur.isSelected() && !jRbRealisateur.isSelected())
            {
                throw new Exception("champ code role vide");
            }
            else
            {
                if(jRbActeur.isSelected()){
                     vip.setCodeRole("A");
                }
                 
                if(jRbRealisateur.isSelected())
                {
                     vip.setCodeRole("R");
                }
                
                if(jRbRealisateur.isSelected() && jRbActeur.isSelected())
                {
                     vip.setCodeRole("AR");
                }
            }
 
            vip.setNomPays(jComboBoxNomPays.getSelectedItem().toString());
            
            if(!jRbMarie.isSelected() && !jRbCelibataire.isSelected())
            {
                throw new Exception("champ code Statut vide");
            }
            else
            {
                if(jRbMarie.isSelected()){
                     vip.setCodeStatut("M");
                }
                else
                {
                     vip.setCodeStatut("C");
                }
            }
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btValidActionPerformed

    private void jTFLieuNaissanceVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFLieuNaissanceVipActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_jTFLieuNaissanceVipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btValid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupCivilite;
    private javax.swing.ButtonGroup buttonGroupCodeStatut;
    private javax.swing.JComboBox<String> jComboBoxNomPays;
    private com.toedter.calendar.JDateChooser jDCDateNaissance;
    private javax.swing.JRadioButton jRbActeur;
    private javax.swing.JRadioButton jRbCelibataire;
    private javax.swing.JRadioButton jRbFemme;
    private javax.swing.JRadioButton jRbHomme;
    private javax.swing.JRadioButton jRbMarie;
    private javax.swing.JRadioButton jRbRealisateur;
    private javax.swing.JTextField jTFLieuNaissanceVip;
    private javax.swing.JTextField jTFNomVip;
    private javax.swing.JTextField jTFPrenomVip;
    private javax.swing.JLabel lbCiviliteVip;
    private javax.swing.JLabel lbCodeRoleVip;
    private javax.swing.JLabel lbCodeStatutVip;
    private javax.swing.JLabel lbDateNaissanceVip;
    private javax.swing.JLabel lbLieuNaissanceVip;
    private javax.swing.JLabel lbNomPaysVip;
    private javax.swing.JLabel lbNomVip;
    private javax.swing.JLabel lbPrenomVip;
    // End of variables declaration//GEN-END:variables
}
