/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Evenement;
import metier.VIP;
import modele.ModeleJComboBox;
import modele.ModeleJTableEvenement;
import modele.ModeleJTableMariage;
import modele.ModeleJTableVip;

/**
 *
 * @author Alain
 */
public class FenetreApplication extends javax.swing.JFrame {

    private ModeleJTableVip leModeleVip;
    private ModeleJTableEvenement leModeleEvenement;
    private ModeleJComboBox leModeleComboBox;
    private ModeleJTableMariage leModelMariage;

    public FenetreApplication(ModeleJTableVip leModeleVip, ModeleJComboBox leModeleComboBox, ModeleJTableEvenement leModeleEvenement, ModeleJTableMariage leModelMariage) {
        this.leModeleVip = leModeleVip;
        this.leModeleComboBox = leModeleComboBox;
        this.leModeleEvenement = leModeleEvenement;
        this.leModelMariage = leModelMariage;
        // initialisation
        initComponents();
        // affichage
        try {
            leModeleVip.chargerLesVip();
            leModeleComboBox.chargerPays();
            leModeleEvenement.chargerLesEvenement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelVip = new javax.swing.JPanel();
        btAjouterVip = new javax.swing.JButton();
        btSupprimerVip = new javax.swing.JButton();
        jSPVip = new javax.swing.JScrollPane();
        jTableVip = new javax.swing.JTable();
        jPanelEvenement = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEvenement = new javax.swing.JTable();
        jBAjouterMariage = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelPhoto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Affichage des employés");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btAjouterVip.setText("Ajouter");
        btAjouterVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterVipActionPerformed(evt);
            }
        });

        btSupprimerVip.setText("Supprimer");
        btSupprimerVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerVipActionPerformed(evt);
            }
        });

        jTableVip.setModel(leModeleVip);
        jSPVip.setViewportView(jTableVip);

        javax.swing.GroupLayout jPanelVipLayout = new javax.swing.GroupLayout(jPanelVip);
        jPanelVip.setLayout(jPanelVipLayout);
        jPanelVipLayout.setHorizontalGroup(
            jPanelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVipLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSupprimerVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAjouterVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jSPVip, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelVipLayout.setVerticalGroup(
            jPanelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVipLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btAjouterVip)
                .addGap(70, 70, 70)
                .addComponent(btSupprimerVip)
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPVip))
        );

        jTabbedPane1.addTab("VIP", jPanelVip);

        jTableEvenement.setModel(leModeleEvenement);
        jScrollPane1.setViewportView(jTableEvenement);

        jBAjouterMariage.setText("Ajouter mariage");
        jBAjouterMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAjouterMariageActionPerformed(evt);
            }
        });

        jButton1.setText("Ajouter divorce");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEvenementLayout = new javax.swing.GroupLayout(jPanelEvenement);
        jPanelEvenement.setLayout(jPanelEvenementLayout);
        jPanelEvenementLayout.setHorizontalGroup(
            jPanelEvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEvenementLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelEvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAjouterMariage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelEvenementLayout.setVerticalGroup(
            jPanelEvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEvenementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelEvenementLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jBAjouterMariage)
                .addGap(112, 112, 112)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Evenement", jPanelEvenement);

        javax.swing.GroupLayout jPanelPhotoLayout = new javax.swing.GroupLayout(jPanelPhoto);
        jPanelPhoto.setLayout(jPanelPhotoLayout);
        jPanelPhotoLayout.setHorizontalGroup(
            jPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhotoLayout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPhotoLayout.setVerticalGroup(
            jPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Photo", jPanelPhoto);

        jTextField1.setEditable(false);
        jTextField1.setText("modifier sup vip car photos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vraiment sortir ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (reponse == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btAjouterVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterVipActionPerformed
        try {
            VIP Vip = new VIP();
            FenetreSaisieVip laSaisieVip = new FenetreSaisieVip(this, Vip, leModeleComboBox);
            if (laSaisieVip.doModal() == true) {
                leModeleVip.insererVip(Vip);
                leModeleVip.rafraichir();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Exception à l'insertion : " + e.getMessage(), "Erreur insertion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAjouterVipActionPerformed

    private void btSupprimerVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerVipActionPerformed
        try {
            int ligne = jTableVip.getSelectedRow();
            leModeleVip.supprimerVIP(ligne);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Exception à la suppression : " + e.getMessage(), "Erreur suppression", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSupprimerVipActionPerformed

    private void jBAjouterMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAjouterMariageActionPerformed
        // TODO add your handling code here:
        try {
            Evenement event = new Evenement();
            FenetreSaisieMariage laSaisieMariage = new FenetreSaisieMariage(this, event, leModelMariage);
            if (laSaisieMariage.doModal() == true) {
                String erreur=leModeleEvenement.insererMariage(event);
                if(erreur!=null){
                    JOptionPane.showMessageDialog(this, "Exception à l'insertion : " + erreur, "Erreur insertion", JOptionPane.ERROR_MESSAGE);
                }
                leModeleEvenement.rafraichir();
                leModeleVip.rafraichir();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Exception à l'insertion : " + e.getMessage(), "Erreur insertion", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jBAjouterMariageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouterVip;
    private javax.swing.JButton btSupprimerVip;
    private javax.swing.JButton jBAjouterMariage;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelEvenement;
    private javax.swing.JPanel jPanelPhoto;
    private javax.swing.JPanel jPanelVip;
    private javax.swing.JScrollPane jSPVip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEvenement;
    private javax.swing.JTable jTableVip;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
