/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Evenement;
import modele.ModeleJTableMariage;

/**
 *
 * @author cyrille
 */
public class FenetreSaisieDivorce extends javax.swing.JDialog {

    private Evenement Event;
    private boolean etatSortie;

    /**
     * Creates new form FenetreSaisieDivorce
     */
    FenetreSaisieDivorce(java.awt.Frame parent, Evenement event) throws SQLException {
        super(parent, true);
        this.Event = event;
        etatSortie = false;
        initComponents();

    }

    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldnumVip = new javax.swing.JTextField();
        jTextFieldDateMariage = new javax.swing.JTextField();
        jTextFieldNumConjoint = new javax.swing.JTextField();
        jTextFieldLieuMariage = new javax.swing.JTextField();
        jLBnumVip = new javax.swing.JLabel();
        jLBdateMariage = new javax.swing.JLabel();
        jLBnumConjoint = new javax.swing.JLabel();
        jLBLieuMariage = new javax.swing.JLabel();
        jDateChooserDateDivorce = new com.toedter.calendar.JDateChooser();
        jLBdateDivorce = new javax.swing.JLabel();
        jBtAjoutDivorce = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldnumVip.setEditable(false);
        jTextFieldnumVip.setText(Integer.toString(Event.getNumVip()));
        jTextFieldnumVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumVipActionPerformed(evt);
            }
        });

        jTextFieldDateMariage.setEditable(false);
        jTextFieldDateMariage.setText(Event.getDateMariage().toString());
        jTextFieldDateMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateMariageActionPerformed(evt);
            }
        });

        jTextFieldNumConjoint.setEditable(false);
        jTextFieldNumConjoint.setText(Integer.toString(Event.getNumConjoint()));

        jTextFieldLieuMariage.setEditable(false);
        jTextFieldLieuMariage.setText(Event.getLieuMariage());
        jTextFieldLieuMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLieuMariageActionPerformed(evt);
            }
        });

        jLBnumVip.setText("num Vip");

        jLBdateMariage.setText("date Mariage");

        jLBnumConjoint.setText("Num Conjoint(e)");

        jLBLieuMariage.setText("Lieu Mariage");

        jLBdateDivorce.setText("Date Divorce");

        jBtAjoutDivorce.setText("Ajout divorce");
        jBtAjoutDivorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAjoutDivorceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLBnumVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldnumVip))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLBdateMariage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDateMariage)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLBdateDivorce, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLBnumConjoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNumConjoint))
                    .addComponent(jDateChooserDateDivorce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldLieuMariage, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLBLieuMariage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtAjoutDivorce)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBnumVip)
                    .addComponent(jLBdateMariage)
                    .addComponent(jLBnumConjoint)
                    .addComponent(jLBLieuMariage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldnumVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNumConjoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldLieuMariage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDateMariage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserDateDivorce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLBdateDivorce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtAjoutDivorce)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLieuMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLieuMariageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLieuMariageActionPerformed

    private void jTextFieldDateMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateMariageActionPerformed

    }//GEN-LAST:event_jTextFieldDateMariageActionPerformed

    private void jTextFieldnumVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumVipActionPerformed

    }//GEN-LAST:event_jTextFieldnumVipActionPerformed

    private void jBtAjoutDivorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAjoutDivorceActionPerformed
        try {
            if (jDateChooserDateDivorce.getCalendar() == null) {
                throw new Exception("champ Date divorce mal rempli");
            } else {
                java.sql.Date dateDivorce = new java.sql.Date(jDateChooserDateDivorce.getDate().getTime());
                if (Event.getDateMariage().compareTo(dateDivorce) == -1) {
                    Event.setDateDivorce(dateDivorce);
                } else {
                    throw new Exception("champ Date de divorce mal rempli");
                }
            }
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jBtAjoutDivorceActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAjoutDivorce;
    private com.toedter.calendar.JDateChooser jDateChooserDateDivorce;
    private javax.swing.JLabel jLBLieuMariage;
    private javax.swing.JLabel jLBdateDivorce;
    private javax.swing.JLabel jLBdateMariage;
    private javax.swing.JLabel jLBnumConjoint;
    private javax.swing.JLabel jLBnumVip;
    private javax.swing.JTextField jTextFieldDateMariage;
    private javax.swing.JTextField jTextFieldLieuMariage;
    private javax.swing.JTextField jTextFieldNumConjoint;
    private javax.swing.JTextField jTextFieldnumVip;
    // End of variables declaration//GEN-END:variables
}
